# Extra autostart processes
# exec-once = uwsm-app -- my-service

exec-once = vicinae server
exec-once = zen-browser
exec-once = google-chrome-stable --profile-directory="Default" --class="chrome-personal" #myself
exec-once = google-chrome-stable --profile-directory="Profile 1" --class="chrome-work" #Aurum"
exec-once = legcord
