# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 5
    # gaps_out = 20
    # border_size = 0

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8
    # Change transparency of focused and unfocused windows
    # active_opacity = 1.0
    # inactive_opacity = 1.0
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}
