# Zen Browser to workspace 1
windowrule = match:class (zen), workspace 1

# Chrome Work profile to workspace 2
windowrule = match:class (chrome-work), workspace 2

# Chrome Personal profile to workspace 2
windowrule = match:class (chrome-personal), workspace 2

# Legcord to workspace 3
windowrule = match:class (legcord), workspace 3
